### ISSUE TITLE
Ao configurar o sistema critica que o setSenderInfo não é um method estatico

### ISSUE THREAD

**Issue by eliasribeiro** [giovannefc/laravel-pagseguro#1]
ao usar o PagSeguro::setSenderInfo($senderInfo)... o sistema informa que o setSenderInfo não é um method static.

**Comment by giovannefc** [comment]
Olá Elias.
Você registrou o ServiceProvider e a Facade?
Outra coisa, veja se você não esqueceu de colocar o:
```php
use PagSeguro;
```
na classe onde você está usando.
Qualquer coisa posta certinho a saída de erro que está dando aqui.

Abs.
