### ISSUE TITLE
Integrações com boleto e débito em conta

### ISSUE THREAD

**Issue by Soufraz** [giovannefc/laravel-pagseguro#2]
Quando faço o include do form, só tem opção de pagamento via cartão de crédito.
Já olhei o arquivo form.blade e realmente não tem nenhuma condição que apresente um form para débito em conta ou boleto.
O pagseguro disponibiliza essa opção na api embutida no site? Ou só consigo usar esses recursos mandando para o pagamento dentro do pagseguro?

**Comment by giovannefc** [comment]
Oi Soufraz. Então, na verdade eu não disponibilizei na view (ainda) um botão pra boleto. Mas é bem simples, basta você fazer um include da view do cartão na sua view de pagamento e criar um botão com o link para pagamento em boleto, você utilizar o método sendBillet. Exemplo:
```php
PagSeguro::setSenderInfo($senderInfo)
->setSenderAddress($senderAddress)
->setItems($items)
->setTotalAmount('150.00')
->sendBillet();
```
Quando ao débito online, existe sim a possibilidade de usar no checkout transparente do pagseguro, mas eu ainda não testei, tem que dar uma olhada na documentação. Assim que sobrar um tempo dou uma olhada e no momento oportuno acrescento esse método.

Vai testando aí, qualquer dúvida ou erro vai dizendo ae!

Abs.
