### ISSUE TITLE
Erro rota pagseguro.send

### ISSUE THREAD

**Issue by welintonInfo** [giovannefc/laravel-pagseguro#5]
Boas, parabéns pela iniciativa ai. 
So tem um problema quando abro a view do pagseguro esta dando esse erro: não existe a rota pagseuro.send

ErrorException in UrlGenerator.php line 314:
Route [pagseguro.send] not defined. (View: /var/www/oni-commerce-base/vendor/giovannefc/laravel-pagseguro/src/Giovannefc/PagSeguro/views/form.blade.php) (View: /var/www/oni-commerce-base/vendor/giovannefc/laravel-pagseguro/src/Giovannefc/PagSeguro/views/form.blade.php)

**Comment by giovannefc** [comment]
Olá Wellington,
você deve criar um controller para enviar a solicitação e definir essa rota no laravel com o nome de `pagseguro.send`.
